export enum Role {
  STUDENT = 'STUDENT',
  CATEGORY_ADMIN = 'CATEGORY_ADMIN',
  MAIN_ADMIN = 'MAIN_ADMIN',
}

export enum UserStatus {
  PENDING = 'PENDING',
  ACTIVE = 'ACTIVE',
  REJECTED = 'REJECTED',
  SUSPENDED = 'SUSPENDED',
}

export enum CategoryName {
  CYBERSECURITY = 'CYBERSECURITY',
  DEVELOPMENT = 'DEVELOPMENT',
  NETWORKING = 'NETWORKING',
  CREATIVE_WORKS = 'CREATIVE_WORKS',
}
